### PR TITLE
Fix shell scripts to run as root

### PR DESCRIPTION
**Pull request by ldclakmal**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by chrishantha** [comment]
Any reason for this change? I don't recommend to use `sudo` over `ssh` for this scenario.

**Comment by ldclakmal** [comment]
Yes. Recently, we did a release of https://github.com/wso2/performance-common, which is (0.4.1) and referred that version as a dependency in https://github.com/ballerina-platform/ballerina-performance. We also removed the cloning and building stage of https://github.com/wso2/performance-common repository from the Jenkins script since it is not needed. Then what happened was, the `netty-http-echo-service.jar` which is wrapped to `ballerina-performance-distribution.tar.gz` could not be executed with the `ubuntu` user, which ended up with some error messages saying "Permission denied".

When I debug the issue, I found that the  permission of `netty-http-echo-service.jar` was different earlier and now. While having the step of cloning and building https://github.com/wso2/performance-common repository, the `.jar` had `-rw-rw-r--` permissions and now it has `-rw-r--r--` permissions. In order to execute that `.jar`, I had to do this fix.

At the moment I am experiencing another issue which says "Pseudo-terminal will not be allocated because stdin is not a terminal." at the stage of starting remote JMeter servers. So, now I am reverting back following 2 lines of this PR.

https://github.com/wso2/performance-common/pull/38/files#diff-4b01d9056d47b630bb298c9b1981050bR480

https://github.com/wso2/performance-common/pull/38/files#diff-4b01d9056d47b630bb298c9b1981050bR565

Please suggest any alternative steps need to done, in order to fix the original issue (which has permission changes).

**Comment by ldclakmal** [comment]
With the above mentioned 2 PRs I reverted this PR and updated the scripts in order to build a stable release version tag (0.4.4.) of performance-common, until we find a proper solution for this.

**Comment by ldclakmal** [comment]
I couldn't find a proper solution other than https://github.com/wso2/performance-common/pull/41. This change is reflected in the release version of `0.4.5`. I used it as the dependency in `ballerina-performance` repository via https://github.com/ballerina-platform/ballerina-performance/pull/51. Removed the step of cloning and building `performance-common` repository.

**Pull request merged**
